import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export default new Vuex.Store({
  state: {
    categories: ['skinCare', 'cleansing', 'maskNpack', 'base', 'eyes', 'lips', 'body', 'suncare'],
    rawData: {
      skinCare: [
        {
          'name': 'DIVE-IN Serum(low molecule hyaluronic acid)',
          'brand': '토리든(torriden)',
          'rank': '1',
          'resellerLink': 'http://www.11st.co.kr/product/SellerProductDetail.tmall?method=getSellerProductDetail&prdNo=2568353400&gclid=Cj0KCQiAiNnuBRD3ARIsAM8Kmlvw2zmR_HSGX9OsX-xyv6OWwJaENYXCVoLaGjsxK1M_OtBqVvlMdOwaAsCGEALw_wcB&utm_term=&utm_campaign=%B1%B8%B1%DB%BC%EE%C7%CEPC+%C3%DF%B0%A1%C0%DB%BE%F7&utm_source=%B1%B8%B1%DB_PC_S_%BC%EE%C7%CE&utm_medium=%B0%CB%BB%F6',
          'imageSource': '스킨케어1',
          'volume': '50ml',
          'price': '28000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': '1025 Dokdo toner',
          'brand': '라운드랩(roundlab)',
          'rank': '2',
          'resellerLink': 'http://www.11st.co.kr/product/SellerProductDetail.tmall?method=getSellerProductDetail&prdNo=2568353400&gclid=Cj0KCQiAiNnuBRD3ARIsAM8Kmlvw2zmR_HSGX9OsX-xyv6OWwJaENYXCVoLaGjsxK1M_OtBqVvlMdOwaAsCGEALw_wcB&utm_term=&utm_campaign=%B1%B8%B1%DB%BC%EE%C7%CEPC+%C3%DF%B0%A1%C0%DB%BE%F7&utm_source=%B1%B8%B1%DB_PC_S_%BC%EE%C7%CE&utm_medium=%B0%CB%BB%F6',
          'imageSource': '스킨케어2',
          'volume': '200ml',
          'price': '15000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Organic aloevera gel',
          'brand': '아로마티카(aromatica)',
          'rank': '3',
          'resellerLink': 'http://aromatica.co.kr/product/%EC%9C%A0%EA%B8%B0%EB%86%8D-%EC%95%8C%EB%A1%9C%EC%97%90-%EB%B2%A0%EB%9D%BC-%EC%A0%A4-limited-edition/83/',
          'imageSource': '스킨케어3',
          'volume': '300ml',
          'price': '11000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Oligo hyaluronic acid 5000 toner',
          'brand': '더랩바이블랑두(THELABbyblancdoux)',
          'rank': '4',
          'resellerLink': 'https://www.coupang.com/vp/products/246379487?itemId=780629226&vendorItemId=5137034838&src=1042503&spec=10304968&addtag=400&ctag=246379487&lptag=GOOGLE_SHOPPING&itime=20191122040101&pageType=PRODUCT&pageValue=246379487&wPcid=15743628611477103115419&wRef=&wTime=20191122040101&redirect=landing&isAddedCart=',
          'imageSource': '스킨케어4',
          'volume': '200ml',
          'price': '21000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'The simple calming toner',
          'brand': '싸이닉(SCINIC)',
          'rank': '5',
          'resellerLink': 'http://shopping.interpark.com/product/productInfo.do?prdNo=6526799370&gclid=Cj0KCQiAiNnuBRD3ARIsAM8Kmlt3sCOgIAXvgxEKN4CIk0Qb_xDguT-DYouIsAgh8Lg4B9TcImSYHAMaAldCEALw_wcB',
          'imageSource': '스킨케어5',
          'volume': '145ml',
          'price': '18000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Cicaful ample',
          'brand': '비플레인(BEPLAIN)',
          'rank': '6',
          'resellerLink': 'http://display.cjmall.com/p/item/59307972?gclid=Cj0KCQiAiNnuBRD3ARIsAM8KmlvptPez8wCIWA4VBA7IRrihavNeiTbTLdARy9L0xiHiCXgxOBKdqQEaArSUEALw_wcB',
          'imageSource': '스킨케어6',
          'volume': '30ml',
          'price': '23000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Wonder ceramide mocchi toner',
          'brand': '토니모리(tonymoly)',
          'rank': '7',
          'resellerLink': 'http://shopping.interpark.com/product/productInfo.do?prdNo=6068539079&gclid=Cj0KCQiAiNnuBRD3ARIsAM8Kmlt0oA-5C8wgEVTSZD3c1YYgk-D6sLw5KcxRKzsO_JQDEEkB_Vq4aXgaArExEALw_wcB',
          'imageSource': '스킨케어7',
          'volume': '500ml',
          'price': '9900',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        }
      ],

      cleansing: [
        {
          'name': 'Sensibio H2O',
          'brand': '바이오더마(bioderma)',
          'rank': '1',
          'resellerLink': 'https://www.coupang.com/vp/products/3673350?itemId=18115589&vendorItemId=3017222271&src=1042503&spec=10304968&addtag=400&ctag=3673350&lptag=GOOGLE_SHOPPING&itime=20191122040650&pageType=PRODUCT&pageValue=3673350&wPcid=15743628611477103115419&wRef=&wTime=20191122040650&redirect=landing&isAddedCart=',
          'imageSource': '클렌징1',
          'volume': '250ml',
          'price': '25000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Clear face spa lip and eye makeup remover',
          'brand': '폰즈(pond\'s)',
          'rank': '2',
          'resellerLink': 'https://www.coupang.com/vp/products/293349108?itemId=926227024&vendorItemId=5301957394&src=1032034&spec=10305201&addtag=400&ctag=293349108&lptag=P293349108&itime=20191122040852&pageType=PRODUCT&pageValue=293349108&wPcid=15743628611477103115419&wRef=prod.danawa.com&wTime=20191122040852&redirect=landing&isAddedCart=',
          'imageSource': '클렌징2',
          'volume': '120ml',
          'price': '9900',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Grante clensing oil',
          'brand': '유리피부(YURIPIBU)',
          'rank': '3',
          'resellerLink': 'http://with.gsshop.com/prd/prd.gs?prdid=50487851&utm_source=google&utm_medium=paid_search&utm_campaign=shopping&gclid=Cj0KCQiAiNnuBRD3ARIsAM8KmlsW-RLLFYjYQ1C9W2T2PByfVPbwxhDQzcq1k_zRPC7suggwbBUfFUMaAh-PEALw_wcB&media=LSC&airbridge_referrer=airbridge=true&event_uuid=2898128a-0c8e-4b72-a810-0d747a562403&transaction_id=0f6b650b-6ee1-4a08-9d16-50df374e04e6&short_id=17cpv&referrer_timestamp=1574363393157&airbridge_tid=0f6b650b-6ee1-4a08-9d16-50df374e04e6',
          'imageSource': '클렌징3',
          'volume': '300ml',
          'price': '36000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Green tea peeling gel',
          'brand': '시드물(SIDMOOL)',
          'rank': '4',
          'resellerLink': 'http://www.sidmool.com/shop/shopdetail.html?branduid=50',
          'imageSource': '클렌징4',
          'volume': '120ml',
          'price': '4800',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Stabilized rice bran enzyme powder wash',
          'brand': '에스알비(SRB)',
          'rank': '5',
          'resellerLink': 'https://front.wemakeprice.com/product/168095014?utm_source=google_ss&utm_medium=cpc&utm_campaign=r_sa&gclid=Cj0KCQiAiNnuBRD3ARIsAM8KmlvxxEi78S48njDEgVGofI2I95iBOXgcd6QYbLls_IxL3V5WgZZ71MQaAg5zEALw_wcB',
          'imageSource': '클렌징5',
          'volume': '70ml',
          'price': '25000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Safe me relief moisture cleansing foam',
          'brand': '메이크프렘(makeprem)',
          'rank': '6',
          'resellerLink': 'http://display.cjmall.com/p/item/52044244?gclid=Cj0KCQiAiNnuBRD3ARIsAM8Kmlss5ZeOVKlnCVHihdjQxh6Z6V9_wNs-W67EW7opHo0wAsr0PRHq5E4aAmWrEALw_wcB',
          'imageSource': '클렌징6',
          'volume': '150ml',
          'price': '16000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Pure balancing cleansing oil',
          'brand': '에이트루(ATRUE)',
          'rank': '7',
          'resellerLink': 'http://display.cjmall.com/p/item/49627513?gclid=Cj0KCQiAiNnuBRD3ARIsAM8KmlvhuKOuJsZNNxDlsyxEnlEhKHWjd2tTYFhBg5RDH4bkY2VIg1f-lYIaAg3PEALw_wcB',
          'imageSource': '클렌징7',
          'volume': '150ml',
          'price': '23000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
      ],
      maskNpack: [
          {
            'name': 'Houttuynia Cordata Mask Sheet',
            'brand': '다자연(allNATURE)',
            'rank': '1',
            'resellerLink': 'http://www.ssg.com/item/itemView.ssg?itemId=1000031456506&ckwhere=ssg_gshopsa&EKAMS=google.723.6063.21630.2037298.616378180&trackingDays=1&gclid=Cj0KCQiAiNnuBRD3ARIsAM8KmluLJ6L42S5Z62-w_jZryy3RNGZPqfDxCX_Qum5w6afb1oLb5gpPkvQaAqroEALw_wcB',
            'imageSource': '팩1',
            'volume': '25ml * 1pack',
            'price': '1500',
            'notes': ['vegan', 'animalTestX', 'organicComponent'],
            'rating': ['4.4', '3243'],
            'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
            'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
            'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
          },
          {
            'name': 'Gummy sheet mask Heartleaf sticker',
            'brand': '아비브(Abib)',
            'rank': '2',
            'resellerLink': 'https://www.wconcept.co.kr/Product/300336824?gclid=Cj0KCQiAiNnuBRD3ARIsAM8KmlvWAsBPxRSZ6LgXowFmsnSTEonFU9NsfCRIfOFMKVeFlSCpq1bzLDoaAh0EEALw_wcB',
            'imageSource': '팩2',
            'volume': '27ml * 1pack',
            'price': '4000',
            'notes': ['vegan', 'animalTestX', 'organicComponent'],
            'rating': ['4.4', '3243'],
            'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
            'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
            'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
          },
          {
            'name': 'Hypoallergenic cica rescue gauze pad',
            'brand': '더마토리(dermatory)',
            'rank': '3',
            'resellerLink': 'http://shopping.interpark.com/product/productInfo.do?prdNo=6299910980&gclid=Cj0KCQiAiNnuBRD3ARIsAM8KmlvIaJ1NN86PbHkWhKfpZghztBh4X5iEWGnIvXGpyciNSc0g-6fWJVAaAmX8EALw_wcB',
            'imageSource': '팩3',
            'volume': '100ml * 60pack',
            'price': '22000',
            'notes': ['vegan', 'animalTestX', 'organicComponent'],
            'rating': ['4.4', '3243'],
            'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
            'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
            'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
          },
          {
            'name': 'Blackbean Mask Sheet',
            'brand': '다자연(allNATURE)',
            'rank': '4',
            'resellerLink': 'http://www.ssg.com/item/itemView.ssg?itemId=1000031456501&ckwhere=ssg_gshopsa&EKAMS=google.723.6063.21630.2037298.616378180&trackingDays=1&gclid=Cj0KCQiAiNnuBRD3ARIsAM8KmltvNITd_QfPFV09J6YKue4HwJwAI-aIXRMXj2c8affZbJ9FynoYKDAaArRKEALw_wcB',
            'imageSource': '팩4',
            'volume': '25ml * 1pack',
            'price': '1500',
            'notes': ['vegan', 'animalTestX', 'organicComponent'],
            'rating': ['4.4', '3243'],
            'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
            'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
            'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
          },
          {
            'name': 'Egg plant clearing mud cream mask',
            'brand': '파파레서피(Paparecipe)',
            'rank': '5',
            'resellerLink': 'http://www.ssg.com/item/itemView.ssg?itemId=1000029571488&ckwhere=ssg_gshopsa&EKAMS=google.723.6063.21629.2037298.600457272&trackingDays=1&gclid=Cj0KCQiAiNnuBRD3ARIsAM8KmlsnVzRhHzLcNwj0A55flz9gcOTl_jTUnEdqWZfBQY9dt24DELi03x0aAsjsEALw_wcB',
            'imageSource': '팩5',
            'volume': '100ml',
            'price': '15000',
            'notes': ['vegan', 'animalTestX', 'organicComponent'],
            'rating': ['4.4', '3243'],
            'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
            'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
            'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
          },
          {
            'name': 'Rotyal honey peptide deep moisture pack',
            'brand': '시드물(SIDMOOL)',
            'rank': '6',
            'resellerLink': 'http://www.sidmool.com/shop/shopdetail.html?branduid=77065',
            'imageSource': '팩6',
            'volume': '40ml',
            'price': '9800',
            'notes': ['vegan', 'animalTestX', 'organicComponent'],
            'rating': ['4.4', '3243'],
            'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
            'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
            'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
          },
          {
            'name': 'Cellmazing centellareal mask pack',
            'brand': '토리든(Torriden)',
            'rank': '7',
            'resellerLink': 'http://shopping.interpark.com/product/productInfo.do?prdNo=6112418398&gclid=Cj0KCQiAiNnuBRD3ARIsAM8Kmlsx9JtYqTAf9z1wMoSd2cdtaTUUWmirmFTyATQ1Ldy0M1ARTIMl-bMaAhXpEALw_wcB',
            'imageSource': '팩7',
            'volume': '22ml * 10pack',
            'price': '22000',
            'notes': ['vegan', 'animalTestX', 'organicComponent'],
            'rating': ['4.4', '3243'],
            'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
            'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
            'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
          }
        ],
      base: [
        {
          'name': 'NO-SEBUM Mineral powder',
          'brand': '이니스프리(innisfree)',
          'rank': '1',
          'resellerLink': 'http://www.11st.co.kr/product/SellerProductDetail.tmall?method=getSellerProductDetail&prdNo=2619520051&gclid=Cj0KCQiAiNnuBRD3ARIsAM8Kmlsja60D3stoX9alMxpUasMM6WHjZ44N0JZFFGxUnOFa5jIz_enQeIwaAkO1EALw_wcB&utm_term=&utm_campaign=%B1%B8%B1%DB%BC%EE%C7%CEPC+%C3%DF%B0%A1%C0%DB%BE%F7&utm_source=%B1%B8%B1%DB_PC_S_%BC%EE%C7%CE&utm_medium=%B0%CB%BB%F6',
          'imageSource': '베이스1',
          'volume': '5g',
          'price': '6000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Art class by Rodin',
          'brand': '투쿨포스쿨(toocoolforschool)',
          'rank': '2',
          'resellerLink': 'http://goods.ellotte.com/goods-fo/goodsDetail/1200944762?chnlNo=100054&chnlDtlNo=1000070&gclid=Cj0KCQiAiNnuBRD3ARIsAM8KmlspasjNQxSngGhYj2-j9h0T8-XTNCRehkF25yE8cjzQLsvnt_PEYiwaAhZ6EALw_wcB',
          'imageSource': '베이스2',
          'volume': '9.5g',
          'price': '16000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Double wear stay in place makeup foundation [SPF10/PA++][1W1]',
          'brand': '에스티로더(ESTEELAUDER)',
          'rank': '3',
          'resellerLink': 'http://www.ssg.com/item/itemView.ssg?itemId=0000000827643&ckwhere=ssg_gshopsa&EKAMS=google.723.6063.21629.2037298.600182562&trackingDays=1&gclid=Cj0KCQiAiNnuBRD3ARIsAM8KmlvchBZNAauF2zVdD-PIP41kCNQY8ZZOPvUPGmLCbNoopIheRAbUTLUaAv1oEALw_wcB',
          'imageSource': '베이스3',
          'volume': '30ml',
          'price': '69000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Double wear stay in place makeup foundation [SPF10/PA++][2C0]',
          'brand': '에스티로더(ESTEELAUDER)',
          'rank': '4',
          'resellerLink': 'http://www.ssg.com/item/itemView.ssg?itemId=0000000827643&ckwhere=ssg_gshopsa&EKAMS=google.723.6063.21629.2037298.600182562&trackingDays=1&gclid=Cj0KCQiAiNnuBRD3ARIsAM8KmlvchBZNAauF2zVdD-PIP41kCNQY8ZZOPvUPGmLCbNoopIheRAbUTLUaAv1oEALw_wcB',
          'imageSource': '베이스4',
          'volume': '30ml',
          'price': '69000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Double wear stay in place makeup foundation [SPF10/PA++][1W2]',
          'brand': '에스티로더(ESTEELAUDER)',
          'rank': '5',
          'resellerLink': 'http://www.ssg.com/item/itemView.ssg?itemId=0000000827643&ckwhere=ssg_gshopsa&EKAMS=google.723.6063.21629.2037298.600182562&trackingDays=1&gclid=Cj0KCQiAiNnuBRD3ARIsAM8KmlvchBZNAauF2zVdD-PIP41kCNQY8ZZOPvUPGmLCbNoopIheRAbUTLUaAv1oEALw_wcB',
          'imageSource': '베이스5',
          'volume': '30ml',
          'price': '69000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'NO-SEBUM Mineral pact',
          'brand': '이니스프리(innisfree)',
          'rank': '6',
          'resellerLink': 'http://www.11st.co.kr/product/SellerProductDetail.tmall?method=getSellerProductDetail&prdNo=2259947248&gclid=Cj0KCQiAiNnuBRD3ARIsAM8KmlvRkeDUpUzN_WaXkoqxb0cSD4b67ukby-LloGjHJnO1zPwU1c4kH38aAlFXEALw_wcB&utm_term=&utm_campaign=%B1%B8%B1%DB%BC%EE%C7%CEPC+%C3%DF%B0%A1%C0%DB%BE%F7&utm_source=%B1%B8%B1%DB_PC_S_%BC%EE%C7%CE&utm_medium=%B0%CB%BB%F6',
          'imageSource': '베이스6',
          'volume': '8.5g',
          'price': '10000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Blush [sexappeal]',
          'brand': '나스(nars)',
          'rank': '7',
          'resellerLink': 'https://www.wconcept.co.kr/Product/300660583?gclid=Cj0KCQiAiNnuBRD3ARIsAM8KmlscC5SF_AwJUX8fAWGYRpP-lxOZkn3EQR6axshEwMP3Vx1_axBxQQoaAtyWEALw_wcB',
          'imageSource': '베이스7',
          'volume': '4.8g',
          'price': '40000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        }
      ],
      eyes: [
        {
          'name': 'Hard formula[02 seal brown]',
          'brand': '슈에무라(shuuemura)',
          'rank': '1',
          'resellerLink': 'http://www.ssg.com/item/itemView.ssg?itemId=1000035331418&ckwhere=ssg_gshopsa&EKAMS=google.723.6063.21629.2037298.600182562&trackingDays=1&gclid=Cj0KCQiAiNnuBRD3ARIsAM8KmltnfSIcJw0yEO5ts5TGPQEYPl4PqJLgNzBOvj1u0uxHcxKmPeUkrnIaAuYNEALw_wcB',
          'imageSource': '아이1',
          'volume': '4g',
          'price': '34000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Look at my eyes[BR422 솔솔말린솔방울]',
          'brand': '에뛰드하우스(ETUDEHOUSE)',
          'rank': '2',
          'resellerLink': 'http://www.11st.co.kr/product/SellerProductDetail.tmall?method=getSellerProductDetail&prdNo=2328168303&gclid=Cj0KCQiAiNnuBRD3ARIsAM8KmlsuYZaYkvsp0AfV5g3UACIfKbYRbmACpw4vt24-PRiM0cbYWjLAZusaAvo0EALw_wcB&utm_term=&utm_campaign=%B1%B8%B1%DB%BC%EE%C7%CEPC+%C3%DF%B0%A1%C0%DB%BE%F7&utm_source=%B1%B8%B1%DB_PC_S_%BC%EE%C7%CE&utm_medium=%B0%CB%BB%F6',
          'imageSource': '아이2',
          'volume': '2g',
          'price': '15000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Heroine make long and curl mascara EX',
          'brand': '키스미(KISSME)',
          'rank': '3',
          'resellerLink': 'https://front.wemakeprice.com/product/139901545?utm_source=google_ss&utm_medium=cpc&utm_campaign=r_sa&gclid=Cj0KCQiAiNnuBRD3ARIsAM8KmlstxJ9oIkJ3f2upRpgvaO6l_9AioEF23Iz5szx7ii9pq45Ya3luJ-EaAr32EALw_wcB',
          'imageSource': '아이3',
          'volume': '6g',
          'price': '11000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Doctor mascara fixer for perfect lash',
          'brand': '에뛰드하우스(ETUDEHOUSE)',
          'rank': '4',
          'resellerLink': 'https://front.wemakeprice.com/product/144562239?search_keyword=%EB%8B%A5%ED%84%B0%20%EB%A7%88%EC%8A%A4%EC%B9%B4%EB%9D%BC%20%ED%94%BD%EC%84%9C&_no=2&_service=5',
          'imageSource': '아이4',
          'volume': '6ml',
          'price': '21000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Oh my lash cara',
          'brand': '에뛰드하우스(ETUDEHOUSE)',
          'rank': '5',
          'resellerLink': 'https://front.wemakeprice.com/product/144561473?search_keyword=%EC%98%A4%20%EB%A7%88%EC%9D%B4%20%EB%9E%98%EC%89%AC%20%EC%B9%B4%EB%9D%BC&_no=2&_service=5',
          'imageSource': '아이5',
          'volume': '7ml',
          'price': '18000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Heroine make smooth liquid eyeliner N [Brown]',
          'brand': '키스미(KISSME)',
          'rank': '6',
          'resellerLink': 'https://front.wemakeprice.com/product/248906358?search_keyword=%ED%9E%88%EB%A1%9C%EC%9D%B8%20%EB%A9%94%EC%9D%B4%ED%81%AC%20%EC%8A%A4%EB%AC%B4%EC%8A%A4&_no=3&_service=5',
          'imageSource': '아이6',
          'volume': '0.4ml',
          'price': '23000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Sharp, so simple waterproof pencil liner[Brown]',
          'brand': '클리오(CLIO)',
          'rank': '7',
          'resellerLink': 'https://front.wemakeprice.com/product/152303710?search_keyword=%EC%83%A4%ED%94%84%20%EC%8F%98%20%EC%8B%AC%ED%94%8C&_no=1&_service=5',
          'imageSource': '아이7',
          'volume': '0.14g',
          'price': '9900',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        }
      ],
      lips: [
        {
          'name': 'Jojoba lip essense',
          'brand': '시드물(SIDMOOL)',
          'rank': '1',
          'resellerLink': 'https://front.wemakeprice.com/product/300390788?search_keyword=%ED%98%B8%ED%98%B8%EB%B0%94%20%EB%A6%BD%20%EC%97%90%EC%84%BC%EC%8A%A4&_no=1&_service=5',
          'imageSource': '립1',
          'volume': '13ml',
          'price': '3800',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Matte lipstick[Chilly]',
          'brand': '맥(MAC)',
          'rank': '2',
          'resellerLink': 'https://front.wemakeprice.com/deal/600094168?search_keyword=%EB%A7%A5%20%EB%A7%A4%ED%8A%B8%20%EB%A6%BD%EC%8A%A4%ED%8B%B1&_no=1&_service=5',
          'imageSource': '립2',
          'volume': '3g',
          'price': '31000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Last velvet lip tint[12 다정보스]',
          'brand': '삐아(Bbia)',
          'rank': '3',
          'resellerLink': 'https://front.wemakeprice.com/product/154305239?search_keyword=%EB%9D%BC%EC%8A%A4%ED%8A%B8%20%EB%B2%A8%EB%B2%B3&_no=1&_service=5',
          'imageSource': '립3',
          'volume': '5g',
          'price': '8500',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Ginger sugar overnight lip mask',
          'brand': '아리따움(aritaum)',
          'rank': '4',
          'resellerLink': 'https://front.wemakeprice.com/product/180991194?search_keyword=%EC%A7%84%EC%A0%80%20%EC%8A%88%EA%B0%80%20%EC%98%A4%EB%B2%84%EB%82%98%EC%9D%B4%ED%8A%B8&_no=1&_service=5',
          'imageSource': '립4',
          'volume': '25g',
          'price': '9000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Sticklerve original',
          'brand': '유리아쥬(URIAGE)',
          'rank': '5',
          'resellerLink': 'https://front.wemakeprice.com/product/300772394?search_keyword=%EC%8A%A4%ED%8B%B1%EB%A0%88%EB%B8%8C%EB%A5%B4&_no=1&_service=1',
          'imageSource': '립5',
          'volume': '4g',
          'price': '12000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Bulgarian rose lip treatment balm[pure red]',
          'brand': '아이소이(isoi)',
          'rank': '6',
          'resellerLink': 'https://front.wemakeprice.com/product/304100515?search_keyword=%EB%B6%88%EA%B0%80%EB%A6%AC%EC%95%88%20%EB%A1%9C%EC%A6%88%20%EB%A6%BD%20%ED%8A%B8%EB%A6%AC%ED%8A%B8%EB%A8%BC%ED%8A%B8%20%EB%B0%A4&_no=1&_service=5',
          'imageSource': '립6',
          'volume': '5g',
          'price': '19800',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Retro matte lipstick[ruby]',
          'brand': '맥(MAC)',
          'rank': '7',
          'resellerLink': 'https://front.wemakeprice.com/deal/600094168?search_keyword=%EB%A7%A5%20%EB%A7%A4%ED%8A%B8%20%EB%A6%BD%EC%8A%A4%ED%8B%B1&_no=1&_service=5',
          'imageSource': '립7',
          'volume': '3g',
          'price': '31000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        }
      ],
      body: [
        {
          'name': 'Pure skin jelly original',
          'brand': '바세린(Vaseline)',
          'rank': '1',
          'resellerLink': 'https://front.wemakeprice.com/product/316256691?source=dealsearch&search_keyword=%EB%B0%94%EC%84%B8%EB%A6%B0&_service=5&no=8&extservice=ad',
          'imageSource': '바디1',
          'volume': '50ml',
          'price': '3000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Ceramide ato lotion',
          'brand': '일리윤(illiyoon)',
          'rank': '2',
          'resellerLink': 'https://front.wemakeprice.com/product/142256896?search_keyword=%EC%84%B8%EB%9D%BC%EB%A7%88%EC%9D%B4%EB%93%9C%20%EC%95%84%ED%86%A0&_no=1&_service=5',
          'imageSource': '바디2',
          'volume': '350ml',
          'price': '19900',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Organic aloe vera gel',
          'brand': '아로마티카(aromatica)',
          'rank': '3',
          'resellerLink': 'https://front.wemakeprice.com/deal/602643543?search_keyword=%EC%95%84%EB%A1%9C%EB%A7%88%ED%8B%B0%EC%B9%B4%20%EC%95%8C%EB%A1%9C%EC%97%90%EB%B2%A0%EB%9D%BC&_no=2&_service=5',
          'imageSource': '바디3',
          'volume': '300ml',
          'price': '11000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Pure and soft feminine wash',
          'brand': '아로마티카(aromatica)',
          'rank': '4',
          'resellerLink': 'https://front.wemakeprice.com/product/152413241?search_keyword=%EC%95%84%EB%A1%9C%EB%A7%88%ED%8B%B0%EC%B9%B4%20%EC%97%AC%EC%84%B1%EC%B2%AD%EA%B2%B0%EC%A0%9C&_no=1&_service=5',
          'imageSource': '바디4',
          'volume': '170ml',
          'price': '15000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Ceramide ato cream',
          'brand': '일리윤(illiyoon)',
          'rank': '5',
          'resellerLink': 'https://front.wemakeprice.com/product/212859835?search_keyword=%EC%9D%BC%EB%A6%AC%EC%9C%A4%EC%84%B8%EB%9D%BC%EB%A7%88%EC%9D%B4%EB%93%9C%EC%95%84%ED%86%A0&_no=5&_service=1',
          'imageSource': '바디5',
          'volume': '200ml',
          'price': '19900',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Daily moisture body lotion',
          'brand': '더마비(Derma:B)',
          'rank': '6',
          'resellerLink': 'https://front.wemakeprice.com/product/323598025?search_keyword=%EB%8D%94%EB%A7%88%EB%B9%84&_no=1&_service=1',
          'imageSource': '바디6',
          'volume': '400ml',
          'price': '16000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Moisturizing lotion',
          'brand': '세타필(Cetaphil)',
          'rank': '7',
          'resellerLink': 'https://front.wemakeprice.com/product/339546032?search_keyword=%EC%84%B8%ED%83%80%ED%95%84%EB%A1%9C%EC%85%98&_no=9&_service=1',
          'imageSource': '바디7',
          'volume': '237ml',
          'price': '14000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        }
      ],
      suncare: [
        {
          'name': 'Premium sun protection suncream [SPF50+/PA+++]',
          'brand': '에이이십사(A24)',
          'rank': '1',
          'resellerLink': 'http://www.wemakeprice.com/deal/adeal/4140922?search_keyword=A24%EC%84%A0%ED%81%AC%EB%A6%BC&_no=1&_service=1',
          'imageSource': '선1',
          'volume': '60ml',
          'price': '38000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': '365 safe suncream [SPF50+/PA++++]',
          'brand': '라운드랩(roundlab)',
          'rank': '2',
          'resellerLink': 'https://front.wemakeprice.com/product/264455790?search_keyword=%EB%9D%BC%EC%9A%B4%EB%93%9C%EB%9E%A9%20%EC%84%A0%ED%81%AC%EB%A6%BC&_no=2&_service=5',
          'imageSource': '선2',
          'volume': '50ml',
          'price': '25000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Razer sunscreen 100 [SPF50+/PA+++]',
          'brand': '셀퓨전씨(CellFusionC)',
          'rank': '3',
          'resellerLink': 'https://front.wemakeprice.com/product/177652585?search_keyword=%EC%85%80%ED%93%A8%EC%A0%84%EC%94%A8%20%EC%8D%AC%EC%8A%A4%ED%81%AC%EB%A6%B0&_no=3&_service=1',
          'imageSource': '선3',
          'volume': '50ml',
          'price': '42000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Green mild up sun [SPF50+/PA++++]',
          'brand': '닥터지(Dr.G)',
          'rank': '4',
          'resellerLink': 'https://front.wemakeprice.com/product/317957582?search_keyword=%EB%8B%A5%ED%84%B0%EC%A7%80%20%EC%84%A0%ED%81%AC%EB%A6%BC&_no=6&_service=5',
          'imageSource': '선4',
          'volume': '50ml',
          'price': '28000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Super food blueberry rebalancing watery suncream [SPF45+/PA+++]',
          'brand': '이니스프리(innisfree)',
          'rank': '5',
          // 'resellerLink': 'https://front.wemakeprice.com/product/168154624?search_keyword=%EC%9D%B4%EB%8B%88%EC%8A%A4%ED%94%84%EB%A6%AC%20%EC%84%A0%ED%81%AC%EB%A6%BC&_no=27&_service=5',
          // 'imageSource': '선5',
          'volume': '40ml',
          'price': '9000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'Urban shade antipollution sun [SPF50+/PA++++]',
          'brand': '듀이트리(Dewytree)',
          'rank': '6',
          'resellerLink': 'https://front.wemakeprice.com/product/130228302?search_keyword=%EB%93%80%EC%9D%B4%ED%8A%B8%EB%A6%AC%20%EC%84%A0%ED%81%AC%EB%A6%BC&_no=1&_service=5',
          'imageSource': '선6',
          'volume': '50ml',
          'price': '30000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        },
        {
          'name': 'UV relief moisturizer [SPF50+/PA++++]',
          'brand': '비레머디스(B:REMEDIES)',
          'rank': '7',
          'resellerLink': 'https://www.bremedies.com/product/%EB%B9%84%EB%A0%88%EB%A8%B8%EB%94%94%EC%8A%A4-uv%EB%A6%B4%EB%A6%AC%ED%94%84-%EB%AA%A8%EC%9D%B4%EC%8A%A4%EC%B2%98%EB%9D%BC%EC%9D%B4%EC%A0%80-spf-50pa-50ml/9/',
          'imageSource': '선7',
          'volume': '50ml',
          'price': '35000',
          'notes': ['vegan', 'animalTestX', 'organicComponent'],
          'rating': ['4.4', '3243'],
          'embededLink1': '<iframe width="560" height="315" src="https://www.youtube.com/embed/qEH7izQ6xmY?start=280" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink2': '<iframe width="560" height="315" src="https://www.youtube.com/embed/yB6SOOeu0Uc?start=349" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
          'embededLink3': '<iframe width="560" height="315" src="https://www.youtube.com/embed/5OuHzaofRso?start=326" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        }
      ]
    }
  },
  mutations:
    {}
  ,
  actions: {}
})
